version: '2'
services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://default:fasFABbrb1QOgyu4pM0f@containers-us-west-33.railway.app:6152"
  proxy_redis:
    image: "redis"
    container_name: proxy_redis
